blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = BlogConfig.name

urlpatterns = [

    path('blog_list/', BlogListView.as_view(), name='blog_list'),
    path('<int:pk>/blog/', BlogDetailView.as_view(), name='blog'),
    path('create/', BlogCreateView.as_view(), name='create_blog'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='update_blog'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_blog'),

]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.views import BlogListView
from catalog.apps import CatalogConfig
from catalog.views import CategoryListView, contacts, ProductListView, ProductDetailView, ProductCreateView, \
    ProductUpdateView, ProductDeleteView, publication

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('contacts/', contacts, name='contacts'),

    path('<int:pk>/products/', ProductListView.as_view(), name='product_list'),
    path('<create/', ProductCreateView.as_view(), name='create_product'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='update_product'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete_product'),
    path('publication/<int:pk>/', publication, name='publication'),
    # path('<int:pk>/product/', ProductDetailView.as_view(), name='product'),
    path('<int:pk>/product/', cache_page(60)(ProductDetailView.as_view()), name='product'),

    path('blog_list/', BlogListView.as_view(), name='blog_list'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog_list/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django import forms
from django.db import models
from django.utils.datetime_safe import date

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование')
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    img = models.ImageField(upload_to='category/', **NULLABLE, verbose_name='Изображение')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'


class Product(models.Model):
    author = models.ForeignKey('users.User', **NULLABLE, on_delete=models.SET_NULL, verbose_name='автор')
    name = models.CharField(max_length=100, verbose_name='Наименование', unique=True)
    description = models.TextField(**NULLABLE, verbose_name='Описание')
    img = models.ImageField(upload_to='product/', **NULLABLE, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    price = models.IntegerField(verbose_name='Цена')
    date_begin = models.DateField(default=date.today, verbose_name='Дата создания')
    date_chang = models.DateField(default=date.today, verbose_name='Дата последнего изменения')
    publication = models.BooleanField(default=False, verbose_name='публикация')

    def __str__(self):
        return f'{self.name} ({self.category})'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ('set_publication', 'Can publication'),
            # ('set_')
        ]


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    number = models.IntegerField(verbose_name='Номер')
    name = models.CharField(max_length=100, verbose_name='Наименование', unique=True)
    activate = models.BooleanField(default=False, verbose_name='Активировать')

    def __str__(self):
        return f'{self.name} ({self.number})'

    class Meta:
        verbose_name = 'версия'
        verbose_name_plural = 'версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'img', 'category', 'price')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            fild.widget.attrs['class'] = 'form-control'

    def clean_name(self):
        cleaned_data = self.cleaned_data.get('name')
        ban_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in ban_words:
            if word in cleaned_data:
                raise forms.ValidationError('Используются запретные слова')
        return cleaned_data

    def clean_description(self):
        cleaned_data = self.cleaned_data.get('description')
        ban_words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']

        for word in ban_words:
            if word in cleaned_data:
                raise forms.ValidationError('Используются запретные слова')
        return cleaned_data


class ModeratorProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ('name', 'description', 'category')

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            for field_name, fild in self.fields.items():
                fild.widget.attrs['class'] = 'form-control'


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        # exclude = ('activate',)
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, fild in self.fields.items():
            if field_name != 'activate':
                fild.widget.attrs['class'] = 'form-control'

catalog/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms import inlineformset_factory
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, ModeratorProductForm
from catalog.models import Category, Product, Version
from catalog.services import get_object_list


class UserHasPermissionMixin:
    def has_permission(self):
        # Проверяем, является ли пользователь владельцем объекта, если да, то разрешаем операцию
        if self.model.objects.get(pk=self.kwargs.get('pk')).author == self.request.user:
            return True
        # если не является, то следуем ограничениям прав permission_required
        return super().has_permission()


class CategoryListView(LoginRequiredMixin, ListView):
    model = Category
    extra_context = {
        'title': 'Категории товаров',
    }

    def get_queryset(self):
        # возвращаем кэшированный queryset, который присвоится к object_list
        return get_object_list(self.model)


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:category')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UserHasPermissionMixin, PermissionRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    permission_required = 'catalog.change_product'

    def get_success_url(self):
        return reverse('catalog:product', args=[self.kwargs.get('pk')])

    def get_form_class(self):
        print(self.object.author)
        print(self.request.user)
        print(self.object.author != self.request.user)
        if self.object.author != self.request.user:
            self.form_class = ModeratorProductForm
        return self.form_class

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        if self.model.author == self.request.user:
            VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
            if self.request.method == 'POST':
                context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
            else:
                context_data['formset'] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()
        else:
            return self.form_invalid(form)
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, UserHasPermissionMixin, PermissionRequiredMixin, DeleteView):
    model = Product
    permission_required = 'catalog.delete_product'
    success_url = reverse_lazy('catalog:category')


class ProductListView(LoginRequiredMixin, ListView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(category_id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        category_item = Category.objects.get(pk=self.kwargs.get('pk'))
        context_data['category_pk'] = category_item.pk,
        context_data['title'] = f'Все товары категории: {category_item.name}'

        return context_data


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(id=self.kwargs.get('pk'))
        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(**kwargs)

        product_item = Product.objects.get(pk=self.kwargs.get('pk'))
        context_data['product_pk'] = product_item.pk,
        context_data['title'] = f'{product_item.name}'

        return context_data


@login_required
@permission_required('catalog.set_publication')
def publication(request, pk):
    product = get_object_or_404(Product, pk=pk)
    cat_pk = product.category.pk
    if product.publication:
        product.publication = False
    else:
        product.publication = True
    product.save()
    return redirect(reverse('catalog:product_list', kwargs={'pk': cat_pk}))


@login_required
def contacts(request):
    context = {
        'title': 'Контакты '
    }
    return render(request, 'catalog/contacts.html', context)

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=5">
    <title>Интернет магазин</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Интернет магазин</h5>
    {% include 'catalog/includes/inc_menu.html' %}
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    {% block content %}
    {% endblock %}
</div>

<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            <p align="center">
                Интернет магазин
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </p>
        </div>
    </div>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <img src="{{object.img|mymedia_filter}}" width="500">
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <h4>Содержимое</h4>
                    {{ object.text }}
                </div>
                <div>
                    Просмотров:
                    {{ object.count_views }}
                </div>
            </div>
            <div>
                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_blog' object.pk %}">Редактировать</a>
                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:delete_blog' object.pk %}">Удалить</a>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="col-12 mb-5">
        <a class="btn btn-outline-primary" href="{% url 'catalog:create_blog' %}">Создать</a>
    </div>
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <img src="{% mymedia_tag object.img %}" width="100">
                        <div>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:blog' object.pk %}">Просмотр</a>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_blog' object.pk %}">Редактировать</a>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:delete_blog' object.pk %}">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
        <div>
    </div>
{% endblock %}

catalog/templates/catalog/category_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="col-12 mb-5">
<!--        {% if user.is_authenticated %}-->
            <a class="btn btn-primary" href="{% url 'catalog:create_product' %}">Добавить товар</a>
<!--        {% endif %}-->
    </div>
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <img src="{% mymedia_tag object.img %}" width="100" height="100" >
                        <div>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_list' object.pk %}">К товарам</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="container">
    <div class="row text-start">
        <div class="col-lg-7 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-5 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
                    </form>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <img src="{% mymedia_tag object.img %}" width="100">
                        <div>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:products' object.pk %}">К товарам</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/product.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <img src="{{object.img|mymedia_filter}}" >
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <h4>Оисание</h4>
                    {{ object.description|description_filter }}
                    <h4>Цена: {{ object.price }} руб. </h4>
                </div>
            </div>
            <a class="p-2 btn btn-outline-primary" href="#">Купить</a>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p> Хотите удалить товар"{{ object.title }}"?</p>
                            <button type="submit" class="btn btn-primary">Подтвердить</button>
                            <a href="{% url 'catalog:category' %}" class="btn btn-primary">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="container">
        <div class="row text-start">
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <img src="{{object.img|mymedia_filter}}" width="500">
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12">
                <div class="card mb-4 box-shadow">
                    <h4>Оисание</h4>
                    {{ object.description|description_filter }}
                    {% for version in object.version_set.all %}
                        {% if version.activate %}
                            <p>Активная версия:{{ version.name }}{{ version.number }}<p>
                        {% endif %}
                    {% endfor %}
                    <h4>Цена: {{ object.price }} руб. </h4>
                </div>
            </div>
            <div class="col-12">
                {% if object.author == user or perms.catalog.change_product %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}">Редактировать</a>
                {% endif %}
                {% if object.author == user or perms.catalog.delete_product %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:delete_product' object.pk %}">Удалить</a>
                {% endif %}
                <a class="p-2 btn btn-outline-primary" href="#">Купить</a>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}
<div class="col-12">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Добавление продукта
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Сохранить</button>
            </div>
            <div class="card-footer"></div>
        </div>
        <div class="col-6">
            <div class="card-header">
                <h3 class="card-title">
                    Версии продукта
                </h3>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                        <hr>
                    {% endif %}
                {% endfor %}
            </div>
            <div class="card-footer"></div>
        </div>
    </form>
</div>

{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% load my_tags %}
{% block content %}
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-4">
                <div class="card mb-4 box-shadow" >
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body" data-height="1000">
                        <img src="{% mymedia_tag object.img %}" width="300" height="300">
                        <div>
                            {% for version in object.version_set.all %}
                                {% if version.activate %}
                                    <p>Активная версия:
                                        {{ version.name }}
                                        {{ version.number }}
                                    <p>
                                {% endif %}
                            {% endfor %}
                        </div>
                        <div>
                            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Описание</a>
                            {% if object.author == user or perms.catalog.change_product %}
                                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:update_product' object.pk %}">Редактировать</a>
                            {% endif %}
                            {% if object.author == user or perms.catalog.delete_product %}
                                <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:delete_product' object.pk %}">Удалить</a>
                            {% endif %}
                            {% if perms.catalog.set_publication %}
                                {% if object.publication %}
                                    <a class="p-2 btn btn-outline-danger" href="{% url 'catalog:publication' object.pk %}">Выкл</a>
                                {% else %}
                                    <a class="p-2 btn btn-outline-success" href="{% url 'catalog:publication' object.pk %}">Вкл</a>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

catalog/templates/catalog/products.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="row text-center">
        {% for object in object_list %}
            <div class="col-3">
                <div class="card mb-4 box-shadow">
                    <div class="card-header">
                        <h4 class="my-0 font-weight-normal">{{ object.name }}</h4>
                    </div>
                    <div class="card-body">
                        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' object.pk %}">Описание</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}